version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: nest_redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nest_network

volumes:
  postgres_data:

networks:
  nest_network:
    driver: bridge
